### ISSUE TITLE
Create an action to let people set their preferred name

### ISSUE THREAD

**Issue by RapidRabbit-11485** [RapidRabbit-11485/PNGTuber-GPT#12]
The biggest reason people use the Teach redeem today is for people to set what the bot should call them. Twitch usernames are terrible read out loud in a lot of cases filled with numbers and other characters. Create an action in Streamer.bot that lets people save their preferred name, and then replace their username on any redeem with the preferred name from the database. Create a command that lets people set a preferred name to be called by the bot.

**Comment by FoxSpellCaster** [comment]
PNGTuber-GPT v1.1 RC1
All commands are performing well except for !setnick. It is generating a preferred_userNames.json file and has filled in "DefaultUser": "Default User", but hasn't been able to add in anything else. I will continue to investigate it myself when I have the time.

**Comment by RapidRabbit-11485** [comment]
I wonder if perhaps it just doesn't set on the first run, because it's seeding the file with a default. Maybe it updates on subsequent runs? Could you upload a log file excerpt for streamer.bot? It may shed some more light on what is happening. I will try some additional testing on my side as well, and see if I can reproduce it.

**Comment by FoxSpellCaster** [comment]
Sorry I am so limited on time right now. (my log files are huge, so I tried to copy the correct part for you)
https://pastebin.com/raw/j3b4AKme
I've tried the basics, restarting, deleting the file, etc.

**Comment by RapidRabbit-11485** [comment]
I think I see the problem from that log excerpt. It's this line:
 'Pronouns' value is either not found or not a valid string.
 
 That seems to make it return false for the method. It needs to handle cases where pronouns are not found more gracefully, and accept it without that. Let me look through the logic a little.

**Comment by RapidRabbit-11485** [comment]
Try removing Line 353:
return false;

This will make the process continue even if pronouns are null, it will simply log that pronouns were not found and should continue. Let me know if that works and I will create a new release.

**Comment by RapidRabbit-11485** [comment]
This issue is being tracked over on this bug report now.
https://github.com/RapidRabbit-11485/PNGTuber-GPT/issues/15

Version 1.1-rc2 was released to address the issue:
https://github.com/RapidRabbit-11485/PNGTuber-GPT/releases/tag/1.1-rc2

**Comment by RapidRabbit-11485** [comment]
Bug #15 was closed as fixed. With no further remaining bugs, I am closing this enhancement as completed. Please open a new enhancement or a bug report if any further modification is needed. Thanks.
