### ISSUE TITLE
SetNick Command Not Working

### ISSUE THREAD

**Issue by JoeStaff** [RapidRabbit-11485/PNGTuber-GPT#15]
The '!setnick' command is failing. I have discovered the issue and resolved it on my end.
The issue revolves around people without a publicly announced pronoun via the 'alejo' website, so the 'pronouns' argument remain blank/null. In the SetPreferredUsername method, I've modified the pronoun string to default to a blank string if a null is returned, then commented out the string 'IsNullOrEmpty' conditional.
```
            //I sexually identify as NULL
            string pronouns = args["Pronouns"].ToString()??"";
            //if (string.IsNullOrWhiteSpace(pronouns))
            //{
            //    CPH.LogError("'Pronouns' value is either not found or not a valid string.");
            //    return false;
            //}

**Comment by RapidRabbit-11485** [comment]
Thanks for reporting the issue. This can also be fixed just by removing line 353 that causes it to return false, shown in your snippet on Line 6. This will cause the process not to fail when the value is null, and it would just remain null. The logic was just incorrect that it should fail the process if not found. I will be publishing a new release to resolve this shortly. Thanks again for your detailed response.

**Comment by RapidRabbit-11485** [comment]
https://github.com/RapidRabbit-11485/PNGTuber-GPT/releases/tag/1.1-rc2

1.1-rc2 has been released to address this issue. Please test and let me know if this issue can be closed. If you continue to encounter an issue, please attach an excerpt of the issue from your streamer.bot log for review. Thanks!

**Comment by JoeStaff** [comment]
Looks good!
