### ISSUE TITLE
Discord link on main website broken

### ISSUE THREAD

**Issue by wahhahahaa** [RapidRabbit-11485/PNGTuber-GPT#20]
Hey, really appreciate ur work on this and just wanted to let you know about the Discord link. 
I have a few ideas that I am trying to create w/ the bot but am struggling with, so I wanted to join the discord to ask. c:

**Comment by RapidRabbit-11485** [comment]
This has been updated. Feel free to come join the discord at https://discord.gg/dbFtJB8J. Unfortunately these expire, because I'm not yet large enough to have a dedicated URL and the invite links expire. Sorry for the inconvenience. Thanks for letting me know.
